repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: git@github.com:famedly/backend-pre-commit-templates.git
    rev: 5414ae52c3eff663ee2e79b4abae1761172bdbc4
    hooks:
    -   id: fmt
    -   id: clippy
-   repo: https://github.com/crate-ci/typos
    rev: typos-dict-v0.11.35
    hooks:
    -   id: typos
