name: Rust

# Trigger the CI on any tags, pushes to any branch and PRs to any branch.
on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "*" ]

# Make sure there is no pipeline running uselessly.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Environment variables for all jobs.
env:
  CARGO_TERM_COLOR: always

# Defined CI jobs.
jobs:
  publish:
    needs: check
    uses: famedly/backend-build-workflows/.github/workflows/publish-crate.yml@v5
    secrets:
      CRATE_REGISTRY_SSH_PRIVKEY: ${{ secrets.CI_SSH_PRIVATE_KEY }}
      CRATE_REGISTRY_AUTH_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    with:
      crate_registry_name: crates-io
      crate_registry_index_url: https://github.com/rust-lang/crates.io-index
  check:
    uses: famedly/backend-build-workflows/.github/workflows/rust-workflow.yml@466f5192d20b5dc7b20718daf5652fbdcbb4c44e
    with:
      ref: 466f5192d20b5dc7b20718daf5652fbdcbb4c44e
    secrets: inherit
