name: Rust

# Trigger the CI on any tags, pushes to any branch and PRs to any branch.
on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "*" ]

# Make sure there is no pipeline running uselessly.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Environment variables for all jobs.
env:
  CARGO_TERM_COLOR: always

# Defined CI jobs.
jobs:
  publish:
    needs: check
    uses: famedly/backend-build-workflows/.github/workflows/publish-crate.yml@fcc2ec82a725d5c4c9c6a8f19e8df101c178dcb6
    secrets:
      CRATE_REGISTRY_SSH_PRIVKEY: ${{ secrets.CI_SSH_PRIVATE_KEY }}
      CRATE_REGISTRY_AUTH_TOKEN: ${{ secrets.SHIPYARD_RS_TOKEN }}
  check:
    uses: famedly/backend-build-workflows/.github/workflows/rust-workflow.yml@fcc2ec82a725d5c4c9c6a8f19e8df101c178dcb6
    secrets: inherit
